In [45]:
import numpy as np

x = np.matrix([[1, 2], [4, 3]])
y = np.matrix([[9, 8], [6, 7]])

In [55]:
print(x)
print(y)


[[1 2]
 [4 3]]
[[9 8]
 [6 7]]


In [93]:
max(3,5)

3

In [86]:
lst_test.append(np.array([5,2,3]))
lst_test

[array([5, 2, 3])]

In [88]:
lst_test.append(np.array([5,5,5]))
lst_test


[array([5, 2, 3]), array([5, 5, 5])]

In [90]:
lst_test[1]=lst_test[1]+ np.array([2,2,2])

In [91]:
lst_test

[array([5, 2, 3]), array([7, 7, 7])]

In [70]:
lst_new=[lst_test[1]] * [2,2,2]
lst_new

TypeError: can't multiply sequence by non-int of type 'list'

In [63]:
lst_test

[[5, 2, 3], [5, 5, 5]]

In [46]:
xysum=x+y

In [47]:
xysum

matrix([[10, 10],
        [10, 10]])

In [56]:
np.multiply(x,y)

matrix([[ 9, 16],
        [24, 21]])

In [50]:
xyprod=np.dot(x,y)

In [51]:
xyprod

matrix([[21, 22],
        [54, 53]])

In [7]:
np.where(x==1,0,x)

array([[0, 2],
       [4, 3]])

In [8]:
x = np.append(x, [7,7])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [40]:
Xlist=[np.array([1,1,1]),np.array([2,2,2]),np.array([[2,3,4],[2,3,4],[2,3,4]])]


In [41]:
type(Xlist)

list

In [44]:
Xlist[0].shape

(3,)

In [37]:
Xlist.append([99*len()])